# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nRtY4ZUR7ox2vRauc68w9ctnUWg_dZsw
"""

import pandas as pd
from sklearn.linear_model import LinearRegression



data={'hours studies':[2,3,4,5,6],
       'test score':[60,70,80,90,95]}
df=pd.DataFrame(data)
x=df[['hours studies']]
y=df['test score']
model=LinearRegression()
model.fit(x,y)

new_hours=[[3.5],[4.5]]
predicted_scores= model.predict(new_hours)
for hours , score in zip(new_hours, predicted_scores):
  print(f"hours studies : {hours[0]},predicted Test score: {score: .2f}")

import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme(style='whitegrid')

sns.scatterplot(data=df, x='hours studies', y='test score', label='Data Points')

sns.regplot(data=df, x='hours studies', y='test score', scatter=False, color='steelblue', label='regression line')

new_hours=[[3.5],[4.5]]
predicted_scores= model.predict(new_hours)

sns.scatterplot(x=[x[0] for x in new_hours],y=predicted_scores, color='red', marker='s', s=100, label='predicted Value')

plt.title('hours studies vs test score')
plt.xlabel('hours studies')
plt.ylabel('test score')

plt.legend()
plt.show()